//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQDemo.EFDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        public DimDate()
        {
            this.FactCallCenters = new HashSet<FactCallCenter>();
            this.FactCurrencyRates = new HashSet<FactCurrencyRate>();
            this.FactFinances = new HashSet<FactFinance>();
            this.FactInternetSales = new HashSet<FactInternetSale>();
            this.FactInternetSales1 = new HashSet<FactInternetSale>();
            this.FactInternetSales2 = new HashSet<FactInternetSale>();
            this.FactProductInventories = new HashSet<FactProductInventory>();
            this.FactResellerSales = new HashSet<FactResellerSale>();
            this.FactResellerSales1 = new HashSet<FactResellerSale>();
            this.FactResellerSales2 = new HashSet<FactResellerSale>();
            this.FactSalesQuotas = new HashSet<FactSalesQuota>();
            this.FactSurveyResponses = new HashSet<FactSurveyResponse>();
        }
    
        public int DateKey { get; set; }
        public System.DateTime FullDateAlternateKey { get; set; }
        public byte DayNumberOfWeek { get; set; }
        public string EnglishDayNameOfWeek { get; set; }
        public string SpanishDayNameOfWeek { get; set; }
        public string FrenchDayNameOfWeek { get; set; }
        public byte DayNumberOfMonth { get; set; }
        public short DayNumberOfYear { get; set; }
        public byte WeekNumberOfYear { get; set; }
        public string EnglishMonthName { get; set; }
        public string SpanishMonthName { get; set; }
        public string FrenchMonthName { get; set; }
        public byte MonthNumberOfYear { get; set; }
        public byte CalendarQuarter { get; set; }
        public short CalendarYear { get; set; }
        public byte CalendarSemester { get; set; }
        public byte FiscalQuarter { get; set; }
        public short FiscalYear { get; set; }
        public byte FiscalSemester { get; set; }
    
        public virtual ICollection<FactCallCenter> FactCallCenters { get; set; }
        public virtual ICollection<FactCurrencyRate> FactCurrencyRates { get; set; }
        public virtual ICollection<FactFinance> FactFinances { get; set; }
        public virtual ICollection<FactInternetSale> FactInternetSales { get; set; }
        public virtual ICollection<FactInternetSale> FactInternetSales1 { get; set; }
        public virtual ICollection<FactInternetSale> FactInternetSales2 { get; set; }
        public virtual ICollection<FactProductInventory> FactProductInventories { get; set; }
        public virtual ICollection<FactResellerSale> FactResellerSales { get; set; }
        public virtual ICollection<FactResellerSale> FactResellerSales1 { get; set; }
        public virtual ICollection<FactResellerSale> FactResellerSales2 { get; set; }
        public virtual ICollection<FactSalesQuota> FactSalesQuotas { get; set; }
        public virtual ICollection<FactSurveyResponse> FactSurveyResponses { get; set; }
    }
}
