//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQDemo.EFDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimSalesReason
    {
        public DimSalesReason()
        {
            this.FactInternetSales = new HashSet<FactInternetSale>();
        }
    
        public int SalesReasonKey { get; set; }
        public int SalesReasonAlternateKey { get; set; }
        public string SalesReasonName { get; set; }
        public string SalesReasonReasonType { get; set; }
    
        public virtual ICollection<FactInternetSale> FactInternetSales { get; set; }
    }
}
