//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQDemo.EFDbFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimScenario
    {
        public DimScenario()
        {
            this.FactFinances = new HashSet<FactFinance>();
        }
    
        public int ScenarioKey { get; set; }
        public string ScenarioName { get; set; }
    
        public virtual ICollection<FactFinance> FactFinances { get; set; }
    }
}
