//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQDemo.EFDbFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorksDW2022Entities : DbContext
    {
        public AdventureWorksDW2022Entities()
            : base("name=AdventureWorksDW2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DatabaseLog> DatabaseLogs { get; set; }
        public DbSet<DimAccount> DimAccounts { get; set; }
        public DbSet<DimCurrency> DimCurrencies { get; set; }
        public DbSet<DimCustomer> DimCustomers { get; set; }
        public DbSet<DimDate> DimDates { get; set; }
        public DbSet<DimDepartmentGroup> DimDepartmentGroups { get; set; }
        public DbSet<DimEmployee> DimEmployees { get; set; }
        public DbSet<DimGeography> DimGeographies { get; set; }
        public DbSet<DimOrganization> DimOrganizations { get; set; }
        public DbSet<DimProduct> DimProducts { get; set; }
        public DbSet<DimProductCategory> DimProductCategories { get; set; }
        public DbSet<DimProductSubcategory> DimProductSubcategories { get; set; }
        public DbSet<DimPromotion> DimPromotions { get; set; }
        public DbSet<DimReseller> DimResellers { get; set; }
        public DbSet<DimSalesReason> DimSalesReasons { get; set; }
        public DbSet<DimSalesTerritory> DimSalesTerritories { get; set; }
        public DbSet<DimScenario> DimScenarios { get; set; }
        public DbSet<FactAdditionalInternationalProductDescription> FactAdditionalInternationalProductDescriptions { get; set; }
        public DbSet<FactCallCenter> FactCallCenters { get; set; }
        public DbSet<FactCurrencyRate> FactCurrencyRates { get; set; }
        public DbSet<FactInternetSale> FactInternetSales { get; set; }
        public DbSet<FactProductInventory> FactProductInventories { get; set; }
        public DbSet<FactResellerSale> FactResellerSales { get; set; }
        public DbSet<FactSalesQuota> FactSalesQuotas { get; set; }
        public DbSet<FactSurveyResponse> FactSurveyResponses { get; set; }
        public DbSet<ProspectiveBuyer> ProspectiveBuyers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<FactFinance> FactFinances { get; set; }
    }
}
